### ISSUE TITLE
Nested folders

### ISSUE THREAD

**Issue by axelboc** [bmatcuk/html-brunch-static#10]
I'd like to group my page templates under `app/pages`. Unfortunately, this means that the output pages end up in `public/pages`. Is there a way around this without having to write my own processor? Could the processor's `transformPath` function be overridable from `html-brunch-static`'s config?

**Comment by bmatcuk** [comment]
Hmm, that's not a bad idea. Unfortunately, I'm about to head out on a trip. When I return, I'll look into implementing this =)

**Comment by bmatcuk** [comment]
Sorry it took me so long to get to this; I've been crazy busy lately!

I've just cut v1.2.0 of [brunch-static](https://github.com/bmatcuk/brunch-static) to add this functionality. There is now an option called `pathTransform` that takes a function that transforms the input path to the output path. In your particular case, you might have a `brunch-config.coffee` that looks something like this:

```coffee
path = require 'path'

exports.config =
  ...
  plugins:
    static:
      pathTransform: (f) -> path.relative 'pages', f
      processors: [
        ...
      ]
```

Let me know if you have any issues!

**Comment by axelboc** [comment]
No worries, thanks heaps!
