### ISSUE TITLE
Custom helper syntax

### ISSUE THREAD

**Issue by JBCSU** [bmatcuk/html-brunch-static#11]
Can you provide an example of how to provide a custom helper? When I do
```
require('html-brunch-static') {
  handlebars:
    enableProcessor: true,
    helpers: {
      ifEq: 'function(a, b, opts) { if (a == b) { return opts.fn(this); } else { return opts.inverse(this); } }'
    }
}
```

I get
```
error: Compiling of app/test.static.hbs failed. ((helpers.ifEq || (depth0 && depth0.ifEq)) || alias2).call is not a function
```

**Comment by bmatcuk** [comment]
Hey jbcsu,

From your code snippet, it looks like you're defining your function as a string (ie, it's surrounded by single quotes). If you change those single quotes to backticks, coffeescript will interpret that as pure javascript and it should work.

```coffeescript
require('html-brunch-static') {
  handlebars:
    enableProcessor: true,
    helpers: {
      ifEq: `function(a, b, opts) { if (a == b) { return opts.fn(this); } else { return opts.inverse(this); } }`
    }
}
```

Alternatively, you could use coffeescript syntax:

```coffeescript
require('html-brunch-static') {
  handlebars:
    enableProcessor: true,
    helpers: {
      ifEq: (a,b,opts) -> if a is b then opts.fn(this) else opts.inverse(this)
    }
}
```

Let me know if that works! =)

**Comment by JBCSU** [comment]
Ah, brilliant, thanks so much! This is my first occasion to use coffeescript, and I'm unfamiliar with the syntax. Thanks for helping me out with such a newbie issue.


-------- Original message --------

**Comment by bmatcuk** [comment]
No worries! Let me know if you run into any more issues!
