### ISSUE TITLE
Can't use partials/layouts with an Angular app

### ISSUE THREAD

**Issue by mattdodge** [bmatcuk/html-brunch-static#12]
Since Angular.js and Handlebars both use the `{{ }}` syntax for wrapping their expressions, it doesn't seem like it's possible to take an existing Angular app with template strings and use HTML Brunch to combine a bunch of partials together. The HTML Brunch plugin will strip any double curly template strings that it doesn't know about.

For example:
```html
---
my_title: Title Goes Here
---
<h1>{{ my_title }}</h1>
<div ng-controller="MyController as ctl">
  {{ ctl.data }}
</div>
```

will compile into this after running through brunch (notice that it removes the controller's data template string).
```html
<h1>Title Goes Here</h1>
<div ng-controller="MyController as ctl">
</div>
```

I know Angular allows you to change how the template strings are interpolated but is there any easier way that I'm not seeing to take an existing angular app and split it into partials using HTML-brunch-static?

**Comment by bmatcuk** [comment]
Sadly, I can't think of any way to do what you want =( Handlebars doesn't have any options to change the `{{...}}` syntax.

**Comment by mattdodge** [comment]
Yeah, that's what I was afraid of too. Since Angular does allow you to change the template delimiter I did that and just did a giant `sed` in my app. I was hoping I was overlooking something simple or another option but that may not be the case. Thanks for getting back though

**Comment by bmatcuk** [comment]
No worries! Sorry I couldn't be more help!
