### ISSUE TITLE
layout.html a reserved name?

### ISSUE THREAD

**Issue by kgcreative** [bmatcuk/html-brunch-static#13]
in `app/pages`, i cannot create `layout.static.hbs`, `layout-%whatever%.static.hbs`, but I can create `lay-out.static.hbs`. This leads me to believe that the name "layout" may be reserved in the system and does not generate a corresponding page, even when used inside the `/pages` folder (instead of `layouts/` or `partials/`). Is this intended behavior?

---
~~edit: I appear to be able to create `%page%-layout.static.hbs`, but not `layout-%page%.static.hbs`~~

**Comment by bmatcuk** [comment]
Well, sort of. The default value of the `layouts` option is just `/layouts?/` which would match directories *and* filenames. You can change the default behavior by changing the `layouts` option to something like: `/\/layouts\//` or `"**/layouts/**"`. This would only match the directory.

**Comment by kgcreative** [comment]
Yep! That did it. Was keeping it open while I made sure it worked on a couple different builds. Thank you!

**Comment by bmatcuk** [comment]
I'm glad that worked for you! =)
