### ISSUE TITLE
changes in layouts and partials during watch won't trigger rebuild

### ISSUE THREAD

**Issue by MartinMalinda** [bmatcuk/html-brunch-static#14]
Current config

```javascript
      processors: [
        require('html-brunch-static')({
          // defaultContext: {},
          // minify: true,
          handlebars: {
            enableProcessor: {
              fileMatch: /\.static\.(hbs|handlebars)$/,
              fileTransform: function(f) {
                return f.replace(/\.static\.\w+$/, '.html')}
            },
            // layouts: /^app\/layouts?/,
            // helpers: {
            //   // probably import these from somewhere
            //   'some-helper': function(input){
            //     return input;
            //   }
            // }
          }
        })
      ]
    }
```

App structure:

```
project
  app
    layouts
      main.static.hbs
    partials
      header.static.hbs
  index.static.hbs
```

Content of `index.static.hbs` is correctly put inside the `main.static.hbs` layout  and `{{>header}}` correctly imports html from `header.static.hbs`.

But only when I change `index.static.hbs` the index.html output is updated. Changes to partial and layout files won't trigger recompile during `brunch watch`. I have to manually restart the server to see the updated changes.

**Comment by MartinMalinda** [comment]
The issue can be reproduced in this repo: rxbugs/static-html-brunch-browsersync . Updating the `main.static.hbs` does not trigger recompilation.

**Comment by MartinMalinda** [comment]
Cool! I tried to dig into source code but unfortunately my experience with Brunch is very limited.. I had to spin up a Gulp project instead.

**Comment by bmatcuk** [comment]
After spending some time looking into this, I've found that it's a bug in brunch v2.9.x. If I downgrade brunch to v2.8.2, it works fine... at least, for the [repository you linked to](https://github.com/rxbugs/static-html-brunch-browsersync).

I've found the problem in brunch's code and I'm going to submit a bug report to them. In the meantime, downgrading to v2.8.x should solve the problem. Can you confirm?

**Comment by MartinMalinda** [comment]
I updated the package.json in that repo to:
```
{
  "name": "simple-brunch",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "start": "brunch watch --server"
  },
  "devDependencies": {
    "browser-sync-brunch": "0.0.9",
    "brunch": "^2.8.2",
    "brunch-static": "^1.2.1",
    "html-brunch-static": "^1.3.1",
    "javascript-brunch": "^2.0.0",
    "sass-brunch": "^2.0.0"
  }
}
```
Still experiencing the same error. Updating main.static.hbs file does not lead to rebuild, only reload.

It was on 2.2.x before so It's probably not caused by error in 2.9.x

**Comment by bmatcuk** [comment]
The caret in `^2.8.2` would still match version 2.9.x as the caret only locks the left-most, non-zero digit (ie, it's the same as `>=2.8.2 <3.0.0`). Try removing the caret (or use `=` instead) and then `npm install`. You can verify your brunch version with `brunch -v`.

The brunch team has [fixed the bug on their end](https://github.com/brunch/brunch/pull/1609), so 2.9.2 (whenever it is released) should work.

**Comment by MartinMalinda** [comment]
@bmatcuk ahh you are right. Just removed the caret and it indeed works. 👍

**Comment by bmatcuk** [comment]
Cool. Hopefully they'll release 2.9.2 soon and this issue will be a thing of the past =)
