### ISSUE TITLE
Partials registration

### ISSUE THREAD

**Issue by dashmug** [bmatcuk/html-brunch-static#15]
Is there another way of registering partials aside from defining them in front matter?

The front matter syntax looks out of place in jade and handlebars files.

Can we auto-register all partials from the `partials` directory instead?

**Comment by bmatcuk** [comment]
Hmm, that's not a bad idea. One potential issue with that is that it would make all of your static files depend on all of the partials. So, when you update a partial, it would cause all of the files to recompile. Might not be an issue in a smaller project, but in a larger project...

I believe you should be able to register all of your partials manually in the `brunch-config.coffee` file, such as:

```coffeescript
exports.config =
  ...
  plugins:
    static:
      processors: [
        require('html-brunch-static') {
          ...
          defaultContext:
            _options:
              partials:
                - app/partials/whatever
                - app/partials/etc
        }
      ]
```

If you had a small number of partials, and you didn't mind if all of your files got recompiled when you changed a partial, this might be an option for you.

**Comment by RuBAN-GT** [comment]
@bmatcuk, thank you for your advice, but this method don't work with layouts. When I try to include partial in layout I get error "*partial could not be fount*", and it only work when I define *_options/partials* with needed files in layout file.

**Comment by bmatcuk** [comment]
@RuBAN-GT Thanks for the heads up! I just cut v1.3.2 which fixes this issue by passing the `defaultContext` on to the layouts. With that and your suggestion, I'll consider this issue closed.

A full example of a `brunch-config.coffee` incorporating RuBAN-GT's suggestion is below. Assuming your partials live in `app/partials`:

```coffee
partials = require('fs').readdirSync('app/partials').map((file) -> "app/partials/#{file}")

exports.config =
  files: {}

  plugins:
    static:
      processors: [
        require('html-brunch-static') {
          defaultContext:
            _options:
              partials: partials
        }
      ]
```

**Comment by fabian-dev** [comment]
As I nested partials down the partials/ folder, I ended up discovering partials recursively.

```javascript
const discoverPartials = (dir) => require('filehound').create().path(dir).ext("hbs").findSync();

exports.plugins = {
    static: {
        processors: [
            require('html-brunch-static')({
                defaultContext: {
                    _options: {
                        partials: discoverPartials("app/partials/")
                    }
                }
            })
        ],
    }
};
```
