### ISSUE TITLE
Custom helper context variable not available at compile time

### ISSUE THREAD

**Issue by pnmcosta** [bmatcuk/html-brunch-static#17]
Hi Guys,

I'm registering a `section` block helper as such:

```
  plugins:
    static:
      processors: [
        require('html-brunch-static') {
          handlebars:
            enableProcessor: true
            helpers: {
              section: (name, options) -> 
                        if !this._sections then this._sections = {}
                        this._sections[name] = options.fn(this)
                        console.log this
                        return null
            }
        }
      ]
```

Usage on the template:
```
{{#section "endbody"}}
<script>
    require("entrada");
</script>
{{/section}}
```

And on the layout:
```
{{{_sections.endbody}}}
```

But the result is always empty.

The console.log on the helper's method, correctly emits the context with the variable(s) as expected.

However a `{{log this}}` on the layout does not include it, which makes me thing that the context variable in not being set at compile.

Could anyone help?

Thanks,
P.

**Comment by pnmcosta** [comment]
FYI, setting it with front matter, works as expected

```
---
_options:
  layout: app/layouts/main.static.hbs
_sections:
  endbody: '<script>require("entrada");</script>'
---
```

However it would be much nicer if we could use blocks.

**Comment by bmatcuk** [comment]
Unfortunately, it seems handlebars helpers aren't meant to be used this way. It's a limitation in the way handlebars works, rather than something I have control over. Sorry =(
