### ISSUE TITLE
Partial within partial "Error: The partial could not be found"

### ISSUE THREAD

**Issue by mattfelten** [bmatcuk/html-brunch-static#18]
I'm getting a confusing error trying to include a partial within another partial.

My use case
`/site/layouts/default.hbs` includes `/site/partials/sidebar.hbs` (this works)
`/site/partials/sidebar.hbs` includes `/site/partials/nav.hbs` (this doesn't)
Each of those references the correct _options: partials: url in the front-matter but it seems like you can only go one level deep. Every normal page fails with `Error: The partial nav could not be found`

I've tried adding both partials to defaultContext also but that doesn't seem to help. Any ideas?

**Comment by bmatcuk** [comment]
This appears to be a bug in the code... I've got a solution half coded up, but I need to run. I'll try to get a fix out this weekend! Sorry for the inconvenience!

**Comment by mattfelten** [comment]
Np! Lmk if I can help test or anything.

**Comment by bmatcuk** [comment]
v1.3.3 should fix this issue =) Let me know if you run into any more problems!

**Comment by mattfelten** [comment]
Thanks!
