### ISSUE TITLE
support for custom helpers

### ISSUE THREAD

**Issue by merunga** [bmatcuk/html-brunch-static#3]
Is there a way to register helpers into handlebars?

**Comment by bmatcuk** [comment]
There is now! In `brunch-config.coffee`, in the handlebars options, you can include a `helpers` hash. This hash is passed verbatim into `Handlebars.registerHelper()`. See the README for more info.

I've updated the version to 1.2.0 and published to npm.

**Comment by merunga** [comment]
thanks!
