### ISSUE TITLE
nested layouts not working

### ISSUE THREAD

**Issue by merunga** [bmatcuk/html-brunch-static#4]
I have two layouts, one defining the other as its "parent", and a bunch of pages setting the first as the layout, but only the content defined in the top-most layout is being rendered.

Are nested layouts supported? That's what I understand from the [first paragraph in the Layouts section in the docs](https://github.com/bmatcuk/html-brunch-static#context-layouts-and-partials).

Thanks!

**Comment by bmatcuk** [comment]
Hmm, it looks like nested layouts were broken. I've fixed the bug and released v1.2.1 to npm =)

**Comment by merunga** [comment]
perfect! amazing response time.
With this one and #3 fixed, I have all I needed.
really appreciate

**Comment by bmatcuk** [comment]
No problem! Glad it's working for you =)
