### ISSUE TITLE
Unable to get a simple example up and running using only handlebars processor

### ISSUE THREAD

**Issue by dagjomar** [bmatcuk/html-brunch-static#5]
please help

**Comment by bmatcuk** [comment]
You'll have to be a lot more specific... what problem are you having? Can you upload your config files or push your project to github so I can take a look?

I've just confirmed that it works fine in brunch v1... brunch v2 "works", but then throws some errors about "cannot read property 'path' of undefined"... I suspect v2 changed something with the way plugins work; I'm looking into that now.

**Comment by dagjomar** [comment]
Sorry for being vague.

With a bit more testing, I got things working with the markdown and jade-files, although I didn't get the my "layout" file to work.

What I tried to do was to only use handlebars, and not markdown and jade files. I created a "index.static.hbs" file with some content, but I didn't see any output of that.

**Comment by bmatcuk** [comment]
I've confirmed that there's some minor issue with Brunch v2.2.0+... I'm still thinking about the best way to fix that. However, it should be possible to use only handlebars. If you could maybe create a github repo with your code, I could point you in the right direction =)

**Comment by dagjomar** [comment]
Ok, well I'm using brunch 1.7.2 I think, so shouldn't be a problem with latest Brunch.

I will try to replicate my problems in a fresh repo...and who knows - it might just work perfectly then :p

**Comment by jahbini** [comment]
I have run head first into many errors of the form "cannot read property 'path' of undefined"  -- as you have mentioned above.  I'm simply trying to duplicate your example.  Where should I look?  What might cause those kind errors?

**Comment by bmatcuk** [comment]
The error is caused by some changes in brunch... I've released v1.1.0 of [brunch-static](https://github.com/bmatcuk/brunch-static) to correct this issue. It should work with previous versions of brunch as well.

**Comment by jahbini** [comment]
Yippee!  It is now working.  I have been using hexo to get my bamboosnow.com site up, but hexo is pretty opinionated about everything being a blog.  brunch-static will fill my needs far better.  thanks.

**Comment by bmatcuk** [comment]
Glad to help =)

@dagjomar: did you ever figure out the issue you were having?

**Comment by holgerw** [comment]
I am having the same problem like @dagjomar.
I am trying to compile a simple html file /app/page.static.hbs.
The debug log shows it gets picked up and compiled with handlebars, but the resulting file is not written to /public.

My config:
```javascript
plugins: {
    static: {
      processors: [
        require('html-brunch-static')({
          handlebars: {
            enableProcessor: true
          }
       })
     ]
   }
}
```
My versions:
"brunch-static": "1.1.1",
"html-brunch-static": "1.2.1",
brunch => 2.6.6

Any hints?

**Comment by bmatcuk** [comment]
Hmm, I've just confirmed that it works with those versions... I've created a quick gist with the files I'm using:

https://gist.github.com/bmatcuk/5fddb13bcf47d5616a5ba2b60caaf53b

If you still can't get it to work, can you upload your files somewhere so I can take a look?

**Comment by holgerw** [comment]
@bmatcuk following your gist I was able to get it working. I guess the problem was my attempt to process a file that did not reference any layout.

Thank you very much for your help and your plugin. It is working great in concert with digest-brunch and gzip-brunch.

**Comment by bmatcuk** [comment]
Hmm, I just tried removing my layout from the project and it still worked... not sure what was going on =( I'm glad you got it working though!
