### ISSUE TITLE
Minify generated HTML

### ISSUE THREAD

**Issue by jacksonrayhamilton** [bmatcuk/html-brunch-static#8]
Is it possible to minify the HTML generated by this plugin? (Specifically, HTML generated by the handlebars processor?) I tried using https://github.com/tolyo/html-pages-brunch, but it doesn't minify the generated HTML.

I have a template `app/index.static.hbs`:

```html
<foo>     <bar>  </bar>   </foo>
```

And the `brunch-config.js`:

```js
module.exports = {
  files: {
    javascripts: {
      joinTo: 'app.js'
    }
  },
  plugins: {
    static: {
      processors: [
        require('html-brunch-static')({
          handlebars: {enableProcessor: true}
        })
      ]
    }
  }
};
```

And the `package.json`:

```json
{
  "devDependencies": {
    "brunch": "^2.8.2",
    "brunch-static": "^1.1.1",
    "html-brunch-static": "^1.2.1",
    "html-pages-brunch": "^2.3.1"
  }
}
```

And running `brunch build --production` does not result in `public/index.html` being minified.

**Comment by bmatcuk** [comment]
Hmm, my guess is that html-pages-brunch is only searching for html files and minifying them... I don't think brunch supports "chaining" of plugins such as hbs -> html via html-brunch-static -> minified via html-pages-brunch. I'll have to add minifying support to this plugin.

I'll look into doing that, but I might not get to it until this weekend.

**Comment by bmatcuk** [comment]
This was actually fairly easy to add, so it's done! =) Newly minted v1.3.0 supports minifying using [html-minifier](https://github.com/kangax/html-minifier). See the `minify` option in the [README](https://github.com/bmatcuk/html-brunch-static#configuration), and see html-minifier for a list of options and their defaults.

Enjoy! =)

**Comment by jacksonrayhamilton** [comment]
Thanks for adding this so quickly! Works well for me.
